# Generated by Django 5.1.3 on 2024-11-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comment",
        ),
    ]
