# Generated by Django 5.1.3 on 2024-11-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(default="None", max_length=256),
        ),
    ]
