# Generated by Django 5.1.3 on 2024-11-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_pr_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="user_acount_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="user_name",
            field=models.CharField(default="User", max_length=50),
        ),
    ]
