# Generated by Django 5.1.3 on 2025-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_user_profile_user_acount_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
