# Generated by Django 5.1.3 on 2025-01-22 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_is_logged_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="PR_content",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(75)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
