# Generated by Django 5.1.3 on 2025-01-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_pr_content_alter_profile_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="PR_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
